backend:
  name: git-gateway

# when using the default proxy server port
local_backend: true

publish_mode: editorial_workflow

# Add the route to your images, so Netlify CMS knows where to save uploads to.
media_folder: "src/assets/images"
public_folder: "/assets/images"

locale: "fr"
display_url: https://dixietime.fr

collections:
  - name: "pages"
    icon: house
    label: "Pages"
    create: false # Change to true to allow editors to create new pages
    delete: false
    files:
      - label: "Accueil"
        name: "index"
        file: "src/content/pages/index.md"
        fields:
          - { label: "Titre", name: "title" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "A propos"
        name: "about"
        file: "src/content/pages/a-propos.md"
        fields:
          - { label: "Titre", name: "title" }
          - { label: "Contenu", name: "body", widget: "markdown" }
          - label: "Musiciens"
            name: "musicians"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Nom", name: "name" }
              - { label: "Instrument", name: "instrument" }
              - { label: "Image", name: "img", widget: image }
      - label: "Actualités"
        name: "blog"
        file: "src/content/pages/actualites.md"
        fields:
          - { label: "Titre", name: "title" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Répertoire"
        name: "repertoire"
        file: "src/content/pages/repertoire.md"
        fields:
          - { label: "Titre", name: "title" }
          - { label: "Contenu", name: "body", widget: "markdown" }
          - label: "Répertoire"
            name: "repertoire"
            widget: "list"
            allow_add: true
            collapsed: false
            label_singular: chanson
            summary: "{{track}}"
            fields:
              - { label: "Nom", name: "track" }
      - label: "Évènements"
        name: "events"
        file: "src/content/pages/evenements.md"
        fields:
          - { label: "Titre", name: "title" }
          - { label: "Contenu", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Actualités"
    label_singular: "Actualité"
    folder: "src/content/posts"
    create: true
    summary: "{{date | date('DD/MM/YYYY')}} - {{title}}"
    sortable_fields:
      fields: [date]
      default:
        field: date
        direction: Descending
    fields:
      - { label: "Titre", name: "title" }
      - {
          label: "Puliée le",
          name: "date",
          widget: "datetime",
          date_format: "dd/MM/yyyy",
        }
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        default: ["concert"]
        fields:
          - name: tag
            label: Tag
            widget: string
        hint: "Séparés par des virgules s'il y en a plusieurs"
      - { label: "Contenu", name: "body", widget: "markdown" }
  - name: "events"
    label: "Évènements"
    label_singular: "Évènement"
    folder: "src/content/events"
    create: true
    summary: "{{start.date | date('DD/MM/YYYY')}} - {{title}} - {{location.place}}"
    sortable_fields:
      fields: [start.date]
      default:
        field: start.date
        direction: Descending
    fields:
      - { label: "Titre", name: "title" }
      - label: "Lieu"
        name: "location"
        widget: "object"
        fields:
          - { label: "Nom", name: "place", widget: "string", required: false }
          - {
              label: "Adresse",
              name: "address",
              widget: "string",
              required: false,
              hint: "Sans le code postal et la ville",
            }
          - {
              label: "Ville",
              name: "city",
              widget: "string",
              required: false,
              hint: "Code postal (optionnel) et ville",
            }
      - label: "Horaires"
        name: "start"
        widget: "object"
        fields:
          - {
              label: "Date",
              name: "date",
              widget: "datetime",
              date_format: "dd/MM/yyyy",
              time_format: false,
            }
          - {
              label: "Heure",
              name: "hour",
              widget: "string",
              hint: "Ex: 20h, A partir de 19h, De 18h à 23h etc.",
              required: false,
            }
      - label: "Tarif"
        name: "price"
        widget: "string"
        required: false
        hint: "Ex: 5€ (Si non rempli, gratuit)"
      - { label: "Contenu", name: "body", widget: "markdown", required: false }
